#!/bin/bash

# checkupdates - checks for updates on local installed scripts and landingpage
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

# version
THISVERSION=1.0

# name of this
MYNAME=$(basename ${0})
# folder for phpdev configuration
CONFIG_DIR="${HOME}/.config/phpdev"
# path to the phpdev configuration file
CONFIG_FILE="${CONFIG_DIR}/config"

# Local scripts to update
LOCAL_SCRIPTS=(
    "adddb" 
    "addsite" 
    "deldb" 
    "delsite" 
    "restartapache" 
    "restartdev" 
    "restartdnsmasq" 
    "restartmailpit" 
    "restartmariadb" 
    "restartnginx" 
    "restartphpfpm" 
    "setrights" 
    "setserver" 
    "setsitephp" 
    "startapache" 
    "startdev" 
    "startdnsmasq" 
    "startmailpit" 
    "startmariadb" 
    "startnginx" 
    "startphpfpm" 
    "stopapache" 
    "stopdev" 
    "stopdnsmasq" 
    "stopmailpit" 
    "stopmariadb" 
    "stopnginx" 
    "stopphpfpm" 
    "xdebug"
)

# Joomla scripts to update
JOOMLA_SCRIPTS=(
    "jbackup" 
    "jbackupall" 
    "jdbdropall" 
    "jdbdump" 
    "jdbdumpall" 
    "jdbimp" 
    "jfunctions" 
    "jlistjoomlas" 
    "joomlainfo" 
    "latestjoomla"
)

LOCAL_SCRIPTS_DIR="/usr/local/bin"
REPO_BASE_URL="https://raw.githubusercontent.com/renekreijveld/macOS_PHP_local_development/main/src"

# show message function
showmessage() {
    if [ "${SILENT}" == "no" ]; then
        echo -e "$1"
    fi
}

# display usage information
usage() {
    echo -e "${MYNAME} ${THISVERSION}, written by René Kreijveld.\n"
    echo -e "Usage: ${MYNAME}\n"
    exit 0
}

check_version() {
    local script="$1"
    local type="$2"
    local local_version repo_version script_path repo_url


    script_path="${LOCAL_SCRIPTS_DIR}/$script"
    
    if [[ -n "$script_path" ]]; then

        # Determine correct repo subfolder (Joomla_scripts or Scripts)
        if [[ "$type" == "script" ]]; then
            local_version=$(grep -E '^THISVERSION=' "$script_path" | cut -d '=' -f2 | tr -d '"')
            repo_url="$REPO_BASE_URL/Scripts/$script"
            repo_version=$(curl -s "$repo_url" | grep -E '^THISVERSION=' | cut -d '=' -f2 | tr -d '"')
        elif [[ "$type" == "joomlascript" ]]; then
            local_version=$(grep -E '^THISVERSION=' "$script_path" | cut -d '=' -f2 | tr -d '"')
            repo_url="$REPO_BASE_URL/Joomla_scripts/$script"
            repo_version=$(curl -s "$repo_url" | grep -E '^THISVERSION=' | cut -d '=' -f2 | tr -d '"')
        elif [[ "$type" == "index" ]]; then
            local_version=$(grep "THISVERSION=" "${ROOTFOLDER}/index.php" | cut -d '=' -f2 | tr -d '"')
            repo_url="$REPO_BASE_URL/Localhost/$script"
            repo_version=$(curl -s "$repo_url" | grep "THISVERSION=" | cut -d '=' -f2 | tr -d '"')
        else
            return
        fi

        if [[ -n "$local_version" && -n "$repo_version" ]]; then
            if [[ "$local_version" != "$repo_version" ]]; then
                echo -e "- update available for $script (installed: $local_version, latest: $repo_version)"
            else
                echo "- $script is up to date (version: $local_version)"
            fi
        fi
    fi
}

check_scripts() {
    echo -e "Checking local scripts:"
    for script in "${LOCAL_SCRIPTS[@]}"; do
        check_version "$script" "script"
    done
}

check_joomla_scripts() {
    echo -e "Checking Joomla scripts:"
    for script in "${JOOMLA_SCRIPTS[@]}"; do
        check_version "$script" "joomlascript"
    done
}

check_landingpage() {
    echo -e "Checking Localhost landingpage:"
    check_version "$script" "index"
}

check_scripts
check_joomla_scripts
check_landingpage