#!/bin/bash

# restartphpfpm - restart the php fpm system services
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

THISVERSION=1.0

# Restart PHP-FPM
brew services restart php@7.4
brew services restart php@8.1
brew services restart php@8.2
brew services restart php@8.3
brew services restart php
