#!/bin/bash

# restartmariadb - restart the mariadb system service
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version
# 1.1 Changed to use stopmariadb and startmariadb scripts
# 1.2 Added -v verbose mode

THISVERSION=1.2

# Restart MariaDB
/usr/local/bin/stopmariadb -v
sleep 3s
/usr/local/bin/startmariadb -v
