#!/bin/bash

# restartphpfpm - restart the php fpm system services
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version
# 1.1 Changed to use stopphpfpm and startphpfpm scripts
# 1.2 Added -v verbose mode

THISVERSION=1.2

/usr/local/bin/stopphpfpm -v
sleep 3s
/usr/local/bin/startphpfpm -v