#!/bin/bash

# restartdev - restart all system services for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version
# 1.1 Use config file and choose between Apache and NginX

THISVERSION=1.1

CONFIG_DIR="${HOME}/.config/phpdev"
CONFIG_FILE="${CONFIG_DIR}/config"

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
    exit 1
fi   

# Restart Dnsmasq
/usr/local/bin/restartdnsmasq

# Restart PHP-FPM
/usr/local/bin/restartphpfpm

if [ "${WEBSERVER}" == "apache" ]; then
    # Restart Apache
    /usr/local/bin/restartapache
fi

if [ "${WEBSERVER}" == "nginx" ]; then
    # Restart NginX
    /usr/local/bin/restartnginx
fi

# Restart MariaDB
/usr/local/bin/restartmariadb

# Restart Mailpit
/usr/local/bin/restartmailpit

