#!/bin/bash

# restartapache - restart the apache system service
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version
# 1.1 Added -v verbose mode

THISVERSION=1.1

# Restart Apache
/usr/local/bin/stopapache -v
sleep 3s
/usr/local/bin/startapache -v
