#!/bin/bash

# restartdnsmasq - restart the dnsmasq system service
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version
# 1.1 Changed to use stopdnsmasq and startdnsmasq scripts

THISVERSION=1.1

# Restart Dnsmasq
/usr/local/bin/stopdnsmasq
sleep 3s
/usr/local/bin/startdnsmasq
