#!/bin/bash

# startdev - start all system services for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version.
# 1.1 Use config file.

VERSION=1.1

CONFIG_DIR="${HOME}/.config/phpdev"
CONFIG_FILE="${CONFIG_DIR}/config"

echo -e "Starting Apache/NginX - MariaDB - PHP development environment services.\n"
echo -e "These services will run in the background and will automatically restart on system reboot.\n"
echo -e "To permanently stop the services, run the stopdev script.\n"

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
    exit 1
fi   

# Start Dnsmasq
/usr/local/bin/startdnsmasq

# Start PHP-FPM
/usr/local/bin/startphpfpm

if [ "${WEBSERVER}" == "apache" ]; then
    # Start Apache
    /usr/local/bin/startapache
fi

if [ "${WEBSERVER}" == "nginx" ]; then
    # Start NginX
    /usr/local/bin/startnginx
fi

# Start MariaDB
/usr/local/bin/startmariadb

# Start Mailpit
/usr/local/bin/startmailpit

# Open landingpage in browser
open "https://localhost"
