#!/bin/bash

# stopphpfpm - stop the phpfpm system services for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

THISVERSION=1.0

# Array of PHP versions
PHP_VERSIONS=("7.4" "8.1" "8.2" "8.3" "8.4" "8.5")

# Stop PHP-FPM
for version in "${PHP_VERSIONS[@]}"; do
    echo "Stop PHP ${version}"
    brew services stop php@${version} > /dev/null
done