#!/bin/bash

# stopmariadb - stop the mariadb system service for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

THISVERSION=1.0

# Stop MariaDB
echo "Stop MariaDB"
brew services stop mariadb > /dev/null
