#!/bin/bash
# jbackup -- backup a Joomla website to a tar.gz file
#
# This scripts supports Joomla versions 1,0.
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version
# 1.1 Added usage
# 1.2 Code rewrite and remove -e option in echos
# 1.3 Typo correction
# 1.4 Added test if jfunctions exists
# 1.5 Added improved tests if files already exist and added -t and -z options

# general variables
MYPATH=$(cd "$(dirname "$0")"; pwd -P)
MYNAME=$(basename "$0")

# folder for phpdev configuration
CONFIG_DIR="${HOME}/.config/phpdev"
# path to the phpdev configuration file
CONFIG_FILE="${CONFIG_DIR}/config"

# Check if jfunctions script exists
if [[ ! -f "${MYPATH}/jfunctions" ]]; then
    echo "Error: Required script 'jfunctions' not found in ${MYPATH}. Exiting."
    exit 1
else
    # Gather Joomla information
    source "${MYPATH}/jfunctions"
fi

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    SITESBACKUP="${PWD}"
fi   

# version
VERSION=1.5

# show message function
showmessage() {
    if [ "${SILENT}" == "no" ]; then
        echo -e "$1"
    fi
}

# display usage information
usage() {
    echo -e "\n${MYNAME} version ${VERSION}, written by Rene Kreijveld.\n"
    echo -e "Usage: ${MYNAME} [-z] [-t] [-o] [-m] [-s] [-h]\n"
    echo "Default action is .tgz backup."
    echo "-z Zip. Backup to a zipfile instead of a tgzfile."
    echo "-t Add a date/time-stamp to the backup file."
    echo "-o Overwrite existing backupfile and/or database dump."
    echo "-s silent, no messages will be shown (optional)."
    echo -e "-h Help. Display this info.\n"
    echo -e "Run ${MYNAME} at the root of your website, where the configuration.php is.\n"
    exit 0
}

ZIP="no"
SILENT="no"
OVERWRITE="no"
TIMESTAMP="no"
while getopts ztosh opt; do
    case "${opt}" in
    z)
        ZIP="yes"
        ;;
    t)
        TIMESTAMP="yes"
        ;;
    o)
        OVERWRITE="yes"
        ;;
    s)
        SILENT="yes"
        ;;
    h)
        usage
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        usage
        ;;
    esac
done

# create date/time stamp
if [ "${TIMESTAMP}" == "yes" ]; then
    NOW=$(date +".%Y%m%d.%H%M%S")
else
    NOW=""
fi

showmessage "${MYNAME} version ${VERSION}, written by Rene Kreijveld."

# Check if database dump exists
if [ -e ${database}.sql ]; then
    if [ "${OVERWRITE}" == "no" ]; then
        echo "Error: Database dump ${database}.sql already exists. Use -o to overwrite."
        exit 1
    fi
fi

if [ "${ZIP}" == "no" ]; then
    BACKUPFILE="${SITESBACKUP}/${sitename}${NOW}.tgz"
else
    BACKUPFILE="${SITESBACKUP}/${sitename}${NOW}.zip"
fi
if [ -e ${BACKUPFILE} ]; then
    if [ "${OVERWRITE}" == "no" ]; then
        echo "Error: backup file ${BACKUPFILE} already exists."
        echo "Use the option -o to overwrite."
        exit 1
    fi
fi

showmessage "This is a Joomla! ${jversion} site. Starting backup ..."

# Check if a .vscode folder exists
if [ -e .vscode ]; then
    VSCODE=".vscode/"
else
    VSCODE=""
fi

# Check if a .git folder exists
if [ -d .git ]; then
    GIT=".git"
else
    GIT=""
fi

# Check if .gitignore exists
if [ -e .gitignore ]; then
    GITIGNORE=".gitignore"
else
    GITIGNORE=""
fi

# check if htaccess is present
if [ -e .htaccess ]
then
    HTACCESS=".htaccess"
else
    HTACCESS=""
fi

showmessage "Create database dump."
jdbdump > /dev/null

showmessage "Create backup."
# create the backup
if [ "${ZIP}" == "no" ]
then
    tar czf ${BACKUPFILE} ${VSCODE} ${GIT} ${GITIGNORE} ${HTACCESS} *
else
    zip -q -r ${BACKUPFILE} ${VSCODE} ${GIT} ${GITIGNORE} ${HTACCESS} *
fi

# Cleanup database dump
rm -f ${database}.sql

showmessage "Your backup is ready at ${BACKUPFILE}."
