#!/bin/bash

# jbackupall - Backup all your local Joomla development websites
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

# define variables

# version
VERSION=1.0

# folder for phpdev configuration
CONFIG_DIR="${HOME}/.config/phpdev"
# path to the phpdev configuration file
CONFIG_FILE="${CONFIG_DIR}/config"

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
    exit 1
fi   

# determine path of script
MYPATH=$(cd "$(dirname "$0")"; pwd -P)
MYNAME=$(basename "$0")

# check if folder for backup storage exists
if [ ! -d "${SITESBACKUP}" ]; then
    echo "Backup directory ${SITESBACKUP} does not exist, exiting."
    exit 1
fi

# Check if jfunctions script exists
if [[ ! -f "${MYPATH}/jfunctions" ]]; then
    echo "Error: Required script 'jfunctions' not found in ${MYPATH}, Exiting."
    exit 1
fi

# display usage information
usage() {
    echo ""
    echo "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
    echo ""
    echo "Usage: ${MYNAME} [-s] [-h]"
    echo ""
    echo "-s Silent. Do not display any messages to standard output."
    echo "-h Help. Display this info."
    echo ""
    exit 0
}

# show message function
showmessage() {
    if [ "${SILENT}" == "no" ]; then
        echo -e "$1"
    fi
}

# display messages
SILENT="no"
# process the arguments
while getopts sh opt; do
    case "${opt}" in
    s)
        SILENT="yes"
        ;;
    h)
        usage
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    esac
done

showmessage "${MYNAME} version ${VERSION}, written by Rene Kreijveld."

for DIR in $(find ${ROOTFOLDER} -maxdepth 4 -type d); do
    if [ -f ${DIR}/configuration.php ]; then
        # possible joomla found
        showmessage "\nPossible Joomla found at ${DIR}."

        # Go to website root folder
        cd ${DIR}

        # Get website information
        source "${MYPATH}/jfunctions"

        # Create backup
        showmessage "Create backup for website ${sitenameclean}."
        jbackup -t -s
        showmessage "Backup for ${sitenameclean} ready."
    fi
done

showmessage "Your website backups are ready in ${SITESBACKUP}."