#!/bin/bash

# jdbdropall -- Drapp all tables from a Joomla database
# Supports Joomla versions 1.0 - 5.x
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history:
# 1.0 Initial version

VERSION=1.0

MYPATH=$(cd "$(dirname "$0")"; pwd -P)
MYNAME=$(basename "$0")

# Check if jfunctions script exists
if [[ ! -f "${MYPATH}/jfunctions" ]]; then
    echo "Error: Required script 'jfunctions' not found in ${MYPATH}. Exiting."
    exit 1
else
    # Gather Joomla information
    source "${MYPATH}/jfunctions"
fi

# Process the arguments
# Inform the user about the process and ask confirmation
echo "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
echo "This is a Joomla! ${jversion} site."
read -p "Press Enter to drop all database tables of this website or press Ctrl-C to abort."

NOW=$(date +".%Y%m%d-%H%M%S")
TMPFILE="./tmp_drop_all_${NOW}.sql"

echo "Dropping all tables..."

echo "SET FOREIGN_KEY_CHECKS = 0;" > "${TMPFILE}"
mariadb-dump --add-drop-table --no-data --host="${host}" --user="${dbuser}" --password="${password}" "${database}" | grep 'DROP TABLE' >> "${TMPFILE}"
echo "SET FOREIGN_KEY_CHECKS = 1;" >> "${TMPFILE}"

mariadb --host="${host}" --user="${dbuser}" --password="${password}" "${database}" < "${TMPFILE}"

rm -f "${TMPFILE}"

echo "All tables have been dropped from the database."