#!/bin/bash

# jdbdropall -- Drapp all tables from a Joomla database
# Supports Joomla versions 1.0 - 5.x
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history:
# 1.0 Initial version

VERSION=1.0

MYPATH=$(cd "$(dirname "$0")"; pwd -P)
MYNAME=$(basename "$0")

# show message function
showmessage() {
    if [ "${SILENT}" == "no" ]; then
        echo -e "$1"
    fi
}

# display usage information

usage() {
    echo -e "\n${MYNAME} ${VERSION}, written by René Kreijveld.\n"
    echo -e "Usage: ${MYNAME} [-f] [-s] [-h]\n"
    echo "-f force, do not ask confirmation before dropping tables."
    echo "-s silent, no messages will be shown (optional)."
    echo -e "-h Help. Display this info.\n"
    echo -e "Run ${MYNAME} at the root of your website, where the configuration.php is.\n"
    exit 0
}

# Process the arguments
SILENT="no"
FORCE="no"
while getopts fsh opt; do
    case "${opt}" in
    f)
        FORCE="yes"
        ;;
    s)
        SILENT="yes"
        ;;
    h)
        usage
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        usage
        ;;
    esac
done

# Inform the user about the process and ask confirmation
showmessage "${MYNAME} ${VERSION}"

# Check if jfunctions script exists
if [[ ! -f "${MYPATH}/jfunctions" ]]; then
    echo "Error: Required script 'jfunctions' not found in ${MYPATH}. Exiting."
    exit 1
else
    # Gather Joomla information
    source "${MYPATH}/jfunctions"
fi

showmessage "This is a Joomla! ${jversion} site."

if [ "${FORCE}" == "no" ]; then
    read -p "Press Enter to drop all database tables of this website or press Ctrl-C to abort."
fi

NOW=$(date +".%Y%m%d-%H%M%S")
TMPFILE="./tmp_drop_all_${NOW}.sql"

showmessage "Dropping all tables..."

echo "SET FOREIGN_KEY_CHECKS = 0;" > "${TMPFILE}"
mariadb-dump --add-drop-table --no-data --host="${host}" --user="${dbuser}" --password="${password}" "${database}" | grep 'DROP TABLE' >> "${TMPFILE}"
echo "SET FOREIGN_KEY_CHECKS = 1;" >> "${TMPFILE}"

mariadb --host="${host}" --user="${dbuser}" --password="${password}" "${database}" < "${TMPFILE}"

rm -f "${TMPFILE}"

showmessage "All tables have been dropped from database ${database}."