#!/bin/bash

# jdbdump -- Dump a Joomla database to SQL file.
# Supports Joomla versions 1.o - 5.x
#
# Copyright 2012+ René Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Version history:
# 1.6 Added use of config file

# General Variables
VERSION=1.6
MYPATH=$(cd "$(dirname "$0")"; pwd -P)
MYNAME=$(basename "$0")
SILENT="no"
# Function to show messages (honoring silent mode)
showmessage() {
    if [[ "${SILENT}" == "no" ]]; then
        echo "$1"
    fi
}

# Check if jfunctions script exists
if [[ ! -f "${MYPATH}/jfunctions" ]]; then
    echo "Error: Required script 'jfunctions' not found in ${MYPATH}. Exiting."
    exit 1
else
    # Gather Joomla information
    source "${MYPATH}/jfunctions"
fi

# Display usage information
usage() {
    echo ""
    echo "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
    echo ""
    echo "Usage: ${MYNAME} [-d] [-c] [-b] [-h]"
    echo ""
    echo "-d Add a date-time-stamp to the database dump filename."
    echo "-c Compress the database dump with gzip."
    echo "-b Save the backup to the default backup folder."
    echo "-h Help. Display this info."
    echo ""
    exit 0
}

# Process the arguments
COMPRESS="no"
SHOWDATE="no"
USEFOLDER="no"
while getopts "dcbh" opt; do
    case "${opt}" in
        d) SHOWDATE="yes" ;;
        c) COMPRESS="yes" ;;
        b) USEFOLDER="yes" ;;
        h) usage ;;
        \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
        :) echo "Option -$OPTARG requires an argument." >&2; exit 1 ;;
    esac
done

# Add a timestamp if requested
if [[ "${SHOWDATE}" == "yes" ]]; then
    NOW=$(date +".%Y%m%d-%H%M%S")
else
    NOW=""
fi

# Inform the user about the process
showmessage "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
showmessage "This is a Joomla! ${jversion} site. Starting database dump..."

DUMP_FILE="${database}${NOW}.sql"

if mysqldump --skip-opt --extended-insert=FALSE --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host="${host}" --user="${dbuser}" --password="${password}" "${database}" > "${DUMP_FILE}"; then
    if [[ "${COMPRESS}" == "yes" ]]; then
        gzip "${DUMP_FILE}"
        showmessage "${DUMP_FILE}.gz created (compressed with gzip)."
        ls -l "${DUMP_FILE}.gz"
    else
        showmessage "${DUMP_FILE} created."
        ls -l "${DUMP_FILE}"
    fi
    exit 0
else
    showmessage "Error creating database dump."
    exit 1
fi