#!/bin/bash

# joomlainfo -- Provide information about this Joomla! installation.
# Supports Joomla 1.0 - 5.x
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version
# 1.1 Code rewrite
# 1.2 Modification of all echo -e statements
# 1.3 Added test if jfunctions exists
# 1.4 Updated display of version number for joomla 4 and up
# 1.5 Code optimisations

VERSION=1.5

MYPATH=$(cd "$(dirname "${0}")" && pwd -P)
MYNAME=$(basename "${0}")

# Include general functions
if [[ ! -e "${MYPATH}/jfunctions" ]]; then
    echo ""
    echo "Error: Cannot continue. Script 'jfunctions' not found in ${MYPATH}."
    echo ""
    exit 1
else
    # shellcheck source=/dev/null
    . "${MYPATH}/jfunctions"
fi

# Output information
echo ""
echo "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
echo ""
echo "This Joomla! website:"
printf "Sitename    : %s\n" "${sitenameclean}"
printf "Version     : %s\n" "${jversion}"
printf "DB Name     : %s\n" "${database}"
printf "DB User     : %s\n" "${dbuser}"
printf "DB Password : %s\n" "${password}"
printf "DB Host     : %s\n" "${host}"
printf "DB Prefix   : %s\n" "${prefix}"
printf "Path        : %s\n" "$(pwd)"
echo ""
