#!/bin/bash

# latestjoomla -- Download and unzip the latest Joomla version
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

VERSION=1.0

# Download latest Joomla version and save as joomla_latest.zip
curl -sL https://www.joomla.org/latest > joomla_latest.zip

# Unzip joomla_latest.zip
unzip -q -o joomla_latest.zip

# Cleanup joomla_latest.zip
rm joomla_latest.zip

# Set correct files and folders rights
/usr/local/bin/setrights
