#!/bin/bash

# joomlainfo -- Provide information about this Joomla! installation.
# Supports Joomla 1.0 - 5.x
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version
# 1.1 Code rewrite
# 1.2 Modification of all echo -e statements
# 1.3 Added test if jfunctions exists
# 1.4 Updated display of version number for joomla 4 and up
# 1.5 Code optimisations
# 1.6 Fixed bug Joomla version

THISVERSION=1.6

MYPATH=$(cd "$(dirname "${0}")" && pwd -P)
MYNAME=$(basename "${0}")

# folder for phpdev configuration
CONFIG_DIR="${HOME}/.config/phpdev"
# path to the phpdev configuration file
CONFIG_FILE="${CONFIG_DIR}/config"

# Display usage information
usage() {
    echo "${MYNAME} ${THISVERSION}, written by René Kreijveld."
    echo -e "\nUsage: ${MYNAME} [-n <name>] [-c] [-h]\n"
    echo "-n the name for the website to show the info of."
    echo "-c show website info compact."
    echo "-h help, display this info.\n"
    exit 0
}

SHOW=""
while getopts n:c opt; do
    case "${opt}" in
    n)
        WEBSITE_NAME=$OPTARG
        ;;
    c)
        SHOW="compact"
        ;;
    h)
        usage
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        usage
        ;;
    esac
done

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
    exit 1
fi   

# Check if WEBSITE_NAME is not empty
if [ ! -z "${WEBSITE_NAME}" ]; then
    WEBSITE_FOLDER=${ROOTFOLDER}/${WEBSITE_NAME}
    cd ${WEBSITE_FOLDER}
fi

# Include general functions
if [[ ! -e "${MYPATH}/jfunctions" ]]; then
    echo "Error: Cannot continue. Script 'jfunctions' not found in ${MYPATH}."
    exit 1
else
    # shellcheck source=/dev/null
    . "${MYPATH}/jfunctions"
fi

# Output information
if [ -z "${SHOW}" ]; then
    echo -e "${MYNAME} ${THISVERSION}\n"
    echo "This Joomla! website:"
    printf "Sitename    : %s\n" "${sitenameclean}"
    printf "Version     : %s\n" "${jversion}"
    printf "DB Name     : %s\n" "${database}"
    printf "DB User     : %s\n" "${dbuser}"
    printf "DB Password : %s\n" "${password}"
    printf "DB Host     : %s\n" "${host}"
    printf "DB Prefix   : %s\n" "${prefix}"
    printf "Path        : %s\n" "$(pwd)"
    echo ""
fi  

if [ "${SHOW}" == "compact" ]; then
    echo "VERSION=${jversion}"
    echo "DATABASE=${database}"
    echo "DBUSER=${dbuser}"
    echo "PASSWORD=${password}"
    echo "HOST=${host}"
    echo "PREFIX=${prefix}"
    echo "PATH=$(pwd)"
fi  
