#!/bin/bash

# adddb - add a new MariaDB database to the local NginX configuration
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

# Variables 
# version
VERSION=1.0
# name of this
MYNAME=$(basename ${0})
# default index.php template
# folder for phpdev configuration
CONFIG_DIR="${HOME}/.config/phpdev"
# path to the phpdev configuration file
CONFIG_FILE="${CONFIG_DIR}/config"

# show message function
showmessage() {
    if [ "${SILENT}" == "no" ]; then
        echo "$1"
    fi
}

# display usage information
usage() {
    echo ""
    echo "${MYNAME} version ${VERSION}, written by René Kreijveld."
    echo ""
    echo "Usage: ${MYNAME} -d <database_name> [-s] [-h]"
    echo ""
    echo " -d the database name for the new website (input without spaces, mandatory)."
    echo " -s silent, no messages will be shown (optional)."
    echo " -h display this help."
    echo ""
    exit 0
}

# Function to check if the site name contains spaces
contains_spaces() {
    if [[ "$1" =~ \  ]]; then
        return 0
    else
        return 1
    fi
}

# Function to check if database exists
database_exists() {
    DATABASE_NAME=$1
    if mysql -u root -p${MARIADBPW} -e "use ${DATABASE_NAME}" 2>/dev/null; then
        return 0
    else
        return 1
    fi
}

# Parse command line arguments
SILENT="no"
while getopts "d:sh" opt; do
    case ${opt} in
    d)
        DATABASE_NAME=$OPTARG
        ;;
    s)
        SILENT="yes"
        ;;
    h)
        usage
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        usage
        ;;
    :)
        echo "Option -$OPTARG requires an argument." >&2
        usage
        ;;
    esac
done

showmessage "${MYNAME} version ${VERSION}, written by René Kreijveld."

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
    exit 1
fi   

source "${CONFIG_FILE}"

showmessage "Add new MariaDB database ${DATABASE_NAME}."

# check if mandatory parameters are provided
if [ -z "${DATABASE_NAME}" ]; then
    echo "Error: -d, no database provided."
    usage
fi

# check if the database name contains spaces
if contains_spaces "${DATABASE_NAME}"; then
    echo "Error: Database name '${DATABASE_NAME}' contains spaces. Please provide a name without spaces."
    exit 1
fi

# Check if the database already exists
if [ ! -z "${DATABASE_NAME}" ]; then
    if database_exists "${DATABASE_NAME}"; then
        echo "Error: The database '${DATABASE_NAME}' already exists."
        exit 1
    fi
fi

if [ ! -z "${DATABASE_NAME}" ]; then
    # Create the database
    if mariadb -u root -p${MARIADBPW} -e "CREATE DATABASE ${DATABASE_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"; then
        showmessage "Database ${DATABASE_NAME} created."
    else
        echo "Error creating database ${DATABASE_NAME}."
        echo "The command was: mariadb -u root -p${MARIADBPW} -e \"CREATE DATABASE ${DATABASE_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;\""
        exit 1
    fi
fi
