#!/bin/bash

# restartdev - restart all system services for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

# Restart Dnsmasq
/usr/local/bin/restartdnsmasq

# Restart PHP-FPM
/usr/local/bin/restartphpfpm

# Restart NginX
/usr/local/bin/restartnginx

# Restart MariaDB
/usr/local/bin/restartmariadb

# Restart Mailpit
/usr/local/bin/restartmailpit

