#!/bin/bash

# restartphpfpm - restart the php fpm system services
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.

# Restart PHP-FPM
brew services restart php@7.4
brew services restart php@8.3
brew services restart php
