#!/bin/bash

echo "Starting NginX - MariaDB - PHP development environment services."
echo "These services will run in the background and will automatically restart on system reboot."
echo "When the Password: prompt appears, enter your password to allow the services to run."
echo " "
echo "To permanently stop the services, run the stopdev script."

# Start Dnsmasq
/usr/local/bin/startdnsmasq

# Start PHP-FPM
/usr/local/bin/startphpfpm

# Start NginX
/usr/local/bin/startnginx

# Start MariaDB
/usr/local/bin/startmariadb

# Start Mailpit
/usr/local/bin/startmailpit

# Open landingpage in browser
open "https://localhost"
