#!/bin/bash

echo "Starting NginX - MariaDB - PHP development environment services."
echo "These services are running in the background and will automatically restart on system reboot."
echo " "
echo "To permanently stop the services, run the stopdev script."

# Start Dnsmasq
/usr/local/bin/startdnsmasq

# Start PHP-FPM
/usr/local/bin/startphpfpm

# Start NginX
/usr/local/bin/startnginx

# Start MariaDB
/usr/local/bin/startmariadb

# Start Mailpit
/usr/local/bin/startmailpit

# Open landingpage in browser
open "https://localhost"
