#!/bin/bash

# stopphpfpm - stop the phpfpm system services for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

VERSION=1.0

# Stop PHP-FPM
brew services stop php@7.4
brew services stop php@8.1
brew services stop php@8.2
brew services stop php@8.3
brew services stop php