#!/bin/bash

# stopdnsmasq - stop the dnsmasq system service for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.

# Stop Dnsmasq
sudo brew services stop dnsmasq
