#!/bin/bash

# stopdev - stop all system services for the development environment
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.

CONFIG_DIR="${HOME}/.config/phpdev"
CONFIG_FILE="${CONFIG_DIR}/config"

echo -e "Stopping Apache/NginX - MariaDB - PHP development environment services.\n"
echo -e "The background services will now be stopped and will not automatically restart on system reboot.\n"

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
    exit 1
fi   

# Stop Mailpit
/usr/local/bin/stopmailpit

# Stop MariaDB
/usr/local/bin/stopmariadb

if [ "${WEBSERVER}" == "apache" ]; then
    # Stop Apache
    /usr/local/bin/stopapache
fi

if [ "${WEBSERVER}" == "nginx" ]; then
    # Stop NginX
    /usr/local/bin/stopnginx
fi

# Stop PHP-FPM
/usr/local/bin/stopphpfpm

# Stop Dnsmasq
/usr/local/bin/stopdnsmasq

echo -e "\nTo start the services again, run the startdev script."
