#!/bin/bash

# xdebug - a xdebug on/off switch for PHP
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

VERSION=1.0

# Syntax: xdebug [on|off]
# This script will enable or disable xdebug by renaming the ext-xdebug.ini file to ext-xdebug.ini.disabled for all installed PHP versions.

OPTION=$1

HOMEBREW_PATH=$(brew --prefix)
BASE_DIR="${HOMEBREW_PATH}/etc/php"

# PHP Versions
PHP_VERSIONS=("7.4" "8.1" "8.2" "8.3" "8.4")

# Rename all ext-xdebug.ini.disabled files to ext-xdebug.ini
xdebug_on() {
    # Find all files named 'ext-xdebug.ini.disabled' in subdirectories and rename them
    find "${BASE_DIR}" -type f -name "ext-xdebug.ini.disabled" | while read -r file; do
        mv "$file" "${file%.disabled}"
    done
}

# Rename all ext-xdebug.ini files to ext-xdebug.ini.disabled
xdebug_off() {
    # Find all files named 'ext-xdebug.ini' in subdirectories and rename them
    find "${BASE_DIR}" -type f -name "ext-xdebug.ini" | while read -r file; do
        mv "${file}" "${file}.disabled"
    done
}

# Get the status of xdebug
xdebug_status() {
    for php_version in "${PHP_VERSIONS[@]}"; do
        if [[ -f "${BASE_DIR}"/${php_version}/conf.d/ext-xdebug.ini ]]; then
            echo "PHP ${php_version}: Xdebug enabled."
        else
            echo "PHP ${php_version}: Xdebug disabled."
        fi   
    done
}


# Process option
if [ "$OPTION" == "on" ]; then
    xdebug_on
elif [ "$OPTION" == "off" ]; then
    xdebug_off
elif [ "$OPTION" == "status" ]; then
    xdebug_status
    exit 0
else
    echo "Invalid option. Usage: xdebug [on|off]"
    exit 1
fi

# Restart PHP FPM
restartphpfpm